version: "3.9"

networks:
  game_net:
    driver: overlay
    attachable: true

services:
  server1:
    image: mp-ws-server:latest
    environment:
      - SERVER_ID=1
    ports:
      - "8081:8080"
    networks:
      - game_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  server2:
    image: mp-ws-server:latest
    environment:
      - SERVER_ID=2
    ports:
      - "8082:8080"
    networks:
      - game_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  server3:
    image: mp-ws-server:latest
    environment:
      - SERVER_ID=3
    ports:
      - "8083:8080"
    networks:
      - game_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  client:
    image: mp-web-client:latest
    ports:
      - "8080:80"
    networks:
      - game_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
